### ISSUE TITLE
No Pushback.exe file

### ISSUE THREAD

**Issue by sdmbtrumpet** [metindikbas/msfs-pushback-helper-app#1]
Unless I am totally glazing over it, I do not see the pushback.exe file that should be ran to load the program anywhere in the folder.  Any help?

**Comment by metindikbas** [comment]
You can download zipped version directly from https://github.com/metindikbas/msfs-pushback-helper-app/releases/download/1.0/PushbackHelper_v1.0.7z

**Comment by sdmbtrumpet** [comment]
Much appreciated.  Will try it out tonight.

**Comment by metindikbas** [comment]
New version is live. Please download https://github.com/metindikbas/msfs-pushback-helper-app/releases/download/2.0/PushbackHelper_v2.0.zip
