### ISSUE TITLE
Speed & going forward

### ISSUE THREAD

**Issue by Kronzky** [metindikbas/msfs-pushback-helper-app#11]
This might seem like a silly request, but when you're doing bushflying sometimes you're getting stuck in the terrain, and a *forward* push would help in that situation.
Also, if the speed would be adjustable, that would be great!

**Comment by metindikbas** [comment]
When there is problem about placement of aircraft or pushback vehicle I am using Y key to activate/deactivate slew mode to let aircraft respawn again. 

About pushback speed, it can be implemented in this app if SimConnect allows to edit pushback speed.

**Comment by VCAmyPopple** [comment]
Speed and direction are both controlled through KEY_TUG_SPEED

KEY_TUG_SPEED | KEY_TUG_SPEED | Triggers tug, and sets desired speed, in feet per second. The speed can be  bothpositive (forward movement) and negative (backward movement).
-- | -- | --

**Comment by alex-johnson** [comment]
#24 is a proposed fix
