### ISSUE TITLE
Request - It is possible to call fuel truck ?

### ISSUE THREAD

**Issue by JLD95** [metindikbas/msfs-pushback-helper-app#14]
Hi,

It is possible to add call fuel truck and adjust fuel quantity ?

**Comment by metindikbas** [comment]
I can add this feature If SimConnect provides support for managing fuel truck. I will check it out.

**Comment by Orbitally** [comment]
I checked and Sim connect doesn't have a viable but couldn't you just have the button trigger a virtual keypress which calls the fuel truck?

**Comment by JLD95** [comment]
Default command is shift F to request fuel.TIALe 20 oct. 2020 20:57, JacobKreindler <notifications@github.com> a écrit :
I checked and Sim connect doesn't have a viable but couldn't you just have the button trigger a virtual keypress which calls the fuel truck?

**Comment by metindikbas** [comment]
@gustavosjp added fuel truck calling feature. It will be released in v2.2

**Comment by JLD95** [comment]
Thank you very much
