### ISSUE TITLE
Program closes right away v2.1

### ISSUE THREAD

**Issue by AndyCYXU** [metindikbas/msfs-pushback-helper-app#15]
Hi I was using your program no problem v 2.1, now i did new w10 install and new FS2020 install and when i run the program it opens momentarily and closes right away??? Why would that happen. Remember its new w10 install so maybe i missing some Net frameworks or something.. well  it does run but closes within couple of seconds. Thanks
I just checked and tried to install Net Framework 4.7.2 and it told me it cannot cause i already have it installed :( so yeah idk

**Comment by metindikbas** [comment]
Hello, Can you please confirm you have installed .Net Framework 4.7.2?

**Comment by AndyCYXU** [comment]
yes it is installed
I downloaded runtime from here https://dotnet.microsoft.com/download/dotnet-framework/net472 and when i ran the install program it told me it 
**".NET Framework 4.7.2 or a later update is already installed on this computer."** and its a shame i used it perfectly fine before dang it amazing little utility

after digging little bit more i was able to find through registry that i have version 4.8 of net framework installed that is why 4.7.2 does not want to install and says that later version is already installed 
realease REG_DWORD value is 528372 and Veriosn REG_SZ 4.8.04084

**Comment by AndyCYXU** [comment]
I tried your version 2.2 still does not work unfortunately, 

NOW on my other computer where I have FS also installed it works just fine but they are both the same have the same stuff installed FML ! and the comp it doesn't work on is the main geez,,,, anyways 

I noticed when i run the file on the other computer i got message from windows PROGRAM WAS PREVENTED FROM STARTING then I had the choice to select RUN ANYWAS or CLOSE it was small BLUE SCREEN, i gotten with some other programs in the past... NOT your usual UserAccountContor screen with YES and NO.. so anyways I selected RUN and it works fine... 

on the computer that i have a problem I don't recall it ever ask me that just from very beginning the program would start and the shut down withing 2-3 seconds. so what i am asking is i think do you know what program (security software) might be responsible for sending this blue window with message that program was prevented from running maybe the darn thing is just not asking me this on the new comp just shuts the program OFF by itself.

 I do not have any AV or any crap running on my PC other then regular windows defender and i even added pushback.exe to exempt programs no luck :( . 

Anyhow I really love the program when i had it running.

**Comment by AndyCYXU** [comment]
THIS IS SO STUPID BUT I SOLVED THE PROBLEM
OK, so i examined exactly what's installed on the computers that run PushBack OK and the only difference was I did not have these 2 things installed

Microsft Visual C++ 2015-2019 Redistributable (x64) - 14.22.27821
Microsft Visual C++ 2015-2019 Redistributable (x86) - 14.22.27821

When installing GeForce Experience it installs them for you and i did not want the GeForce so i didn't install it on my main FS computer, well instead of searching for these packages i just went ahead and installed the GeForce which installed the damn Redistributable and the F$#@ing PROGRAM WORKS !!!!

I guess you can consider this solved and yeah these two things are needed for your program to run!
