### ISSUE TITLE
Possible Additional Features

### ISSUE THREAD

**Issue by Orbitally** [metindikbas/msfs-pushback-helper-app#17]
I was wondering if you could add support for: Baggage, Catering, Fuel Truck, & an option to change which key triggers the popup.

**Comment by kiven112** [comment]
Hey, I fly alot in scandinavia meaning I usually park at stands. If it is possible I would love to see a function to connect a ramp and possibly have it connected until otherwise told. Thanks for your hard work!

**Comment by Trigger87** [comment]
Hey, i realy love your pushback helper. I'm playing with Self Loading Cargo and my problem is the same with the fast docking and undocking ramp truck. Its way too fast and the front doors is open for 4-5 passengers only. (A320 can carry up to 190people...lol)
> If it is possible I would love to see a function to connect a ramp and possibly have it connected until otherwise told

If the ramp truck is too complicated to do -> maybe you could add a button to open/close the Door 01 of the plane? It would help me very much, even without the ramp truck :) 

Thanks for your great work! This mod makes pushback a lot easier.

**Comment by Orbitally** [comment]
> Hey, i realy love your pushback helper. I'm playing with Self Loading Cargo and my problem is the same with the fast docking and undocking ramp truck. Its way too fast and the front doors is open for 4-5 passengers only. (A320 can carry up to 190people...lol)
> 
> > If it is possible I would love to see a function to connect a ramp and possibly have it connected until otherwise told
> 
> If the ramp truck is too complicated to do -> maybe you could add a button to open/close the Door 01 of the plane? It would help me very much, even without the ramp truck :)
> 
> Thanks for your great work! This mod makes pushback a lot easier.

Can we get access to your program yet or is it not public yet?

**Comment by Trigger87** [comment]
"KEY_TOGGLE_AIRCRAFT_EXIT" should work for the door. I hope you can implement it :)

**Comment by alex-johnson** [comment]
I don't see any way to call the catering or baggage via SimConnect. Anyone have any ideas? Absolutely nothing in the SDK.

**Comment by alex-johnson** [comment]
I found out how to do catering, luggage, power, and stair truck. Will have it added soon.
