### ISSUE TITLE
Missing file in master branch

### ISSUE THREAD

**Issue by davidbonnici1984** [metindikbas/msfs-pushback-helper-app#22]
![image](https://user-images.githubusercontent.com/905774/103882608-5d1ad980-50dc-11eb-8563-5334e92000df.png)

IOException: Cannot locate resource 'images/xd/doorbutton.png'.

**Comment by davidbonnici1984** [comment]
Files are present but not included in the project. I fixed this in a separate branch but I don't have permission to push the branch and create PR.

**Comment by davidbonnici1984** [comment]
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --set-upstream origin assets_include_fix:assets_include_fix
remote: Permission to metindikbas/msfs-pushback-helper-app.git denied to davidbonnici1984.
fatal: unable to access 'https://github.com/metindikbas/msfs-pushback-helper-app.git/': The requested URL returned error: 403
Pushing to https://github.com/metindikbas/msfs-pushback-helper-app.git
Completed with errors, see above.

**Comment by alex-johnson** [comment]
@davidbonnici1984 You have to fork, commit to your fork, and request a PR from your fork. My PR will fix this issue though - I've reworked the UI so that text isn't hard coded into the button graphics.

**Comment by davidbonnici1984** [comment]
Ahh yeah, ok cheers.

Nice removing the hardcoded text within the graphics!

**Comment by alex-johnson** [comment]
#24 will resolve

**Comment by metindikbas** [comment]
Hello, I have fixed the errors from previous merge operation. The contribution had problems and I did not see on merge.
I will merge it with @alex-johnson 's requests and will publish new release. 

I am sorry for delay :(
