### ISSUE TITLE
Enhancement: possibility to adjust Tug speed

### ISSUE THREAD

**Issue by JLD95** [metindikbas/msfs-pushback-helper-app#28]
Hi,
In a configuration file for example, it will be nice if we have a possibility to adjust the TU speed ?
The older version have a correct speed but now, it is too high.

**Comment by alex-johnson** [comment]
I can add a slider for tug speed to the UI when I have time. Saving last value to config would be trivial too.

**Comment by Iunoi** [comment]
Yeah would be great! My Tug is way to fast 😀

**Comment by alex-johnson** [comment]
See #29

**Comment by JLD95** [comment]
thank you very much. Is it normal to have the same number version v2.3 for this new software ?

**Comment by alex-johnson** [comment]
Nope. Just a little confusion between devs. I thought it was put up on flightsim.to as v2.3 so I renamed it to v2.3 here. Turns out the file on flightsim.to is the older v2.3.

edit: okay renaming version with tug speed to v2.4
