### ISSUE TITLE
Missing "Straight" button (enhancement)

### ISSUE THREAD

**Issue by frankkopp** [metindikbas/msfs-pushback-helper-app#31]
Missing the straight button. Once left or right is used it is not possible to go straight anymore. 
(or am I missing how this works?)

**Comment by alex-johnson** [comment]
If going reverse, click the reverse button again to straighten out. If going forward, click the forward button again. Hope that makes sense

**Comment by frankkopp** [comment]
> If going reverse, click the reverse button again to straighten out. If going forward, click the forward button again. Hope that makes sense
