### ISSUE TITLE
App doesn't shutdown any more when MSFS is shutdown

### ISSUE THREAD

**Issue by parlock** [metindikbas/msfs-pushback-helper-app#33]
The app no longer shuts down when MSFS shuts down.  Causing an issue if you relaunch MSFS as it crashes when its already running and it tries to start it up again...

**Comment by alex-johnson** [comment]
Previously the app wasn't really shutting down so much as crashing upon quitting MSFS. I think adding auto-shutdown is a good idea though.

**Comment by parlock** [comment]
That would be great.  Then it will auto start/shutdown with MSFS...

**Comment by alex-johnson** [comment]
@parlock  https://github.com/alex-johnson/msfs-pushback-helper-app/releases/download/beta/MSFS-Pushback-Helper-App-beta.zip will resolve

Not pulled into main repo just yet

**Comment by parlock** [comment]
@alex-johnson Its working great for me!!!  Thanks for the update

**Comment by parlock** [comment]
One thing I have noticed lately.  Is the app comes up very small on the UI.  I have tried even waiting and manually starting it and it sometimes does come up tiny.  Then I have to manually resize the window...

**Comment by alex-johnson** [comment]
@parlock I noticed that as well. It happens when the app is closed while minimized. It saves the last size on close, but if the app is minimized it must be reporting as zero size. On next start it will try to open with zero size but instead gets kicked up to the minimum allowed size.

**Comment by parlock** [comment]
@alex-johnson I took your version and just commented out the height reset line on startup.  that's working for me now.  But ideally I guess it should save those settings when you move/resize it.  Not on exit..

**Comment by alex-johnson** [comment]
@parlock I fixed it in my latest beta I believe. You can grab it here:
https://github.com/alex-johnson/msfs-pushback-helper-app/releases/download/beta/MSFS-Pushback-Helper-App-beta.zip

Waiting for it to get pulled into this repo by @metindikbas
