### ISSUE TITLE
Crashes in about 5 seconds.

### ISSUE THREAD

**Issue by flightsimguy24** [metindikbas/msfs-pushback-helper-app#35]
Since 2.1 or 2.2, this has been crashing after about 5 seconds and not connecting to the sim.

**Comment by AdamApples** [comment]
I've just downloaded this app and have the same problem. does NOT connect and crashes after about 5 seconds.

**Comment by flightsimguy24** [comment]
i found a fix. if you remove everything from the zip onto your desktop it seems to work.

**Comment by alex-johnson** [comment]
I'm not sure I follow, can you provide a little more detail on that fix? Were you running it from the zip file?

**Comment by flightsimguy24** [comment]
Sure. After I downloaded it , I took out all the files/programs in the zip (simconnect.dll etc.), and put them on the desktop. I simply leave the files/programs on the desktop and it runs just fine.
