### ISSUE TITLE
Application v2.4 doesn't start.

### ISSUE THREAD

**Issue by Biniou671** [metindikbas/msfs-pushback-helper-app#38]
When clicking the Icon, or the file .exe, nothing happens.
I already tried to uninstall and re-install, issue still there.
This happen since last 2 weeks.

**Comment by g0wfv** [comment]
Have you got all the files in the same directory? What I mean is you've not just taken .exe out the directory on its own instead of creating a shortcut to it?

**Comment by alex-johnson** [comment]
v2.5 is out, does that resolve the issue?

**Comment by metindikbas** [comment]
There is no update from the reporter and there are newer versions.
