### ISSUE TITLE
Does not display on visible screen area

### ISSUE THREAD

**Issue by g0wfv** [metindikbas/msfs-pushback-helper-app#39]
Last screen position is remembered and restored on application start.  If used on a lower resolution monitor from that last used, application can start outside the visibile screen area with no way of moving it.

**Comment by andreas-paul** [comment]
I had this issue as well. What solved it for me was to start Pushbackhelper.exe, hold shift and right click on the app in the taskbar, and select 'move', then use the keyboard arrow keys or your mouse to move the app back into view.
