### ISSUE TITLE
Button control

### ISSUE THREAD

**Issue by sschw56** [metindikbas/msfs-pushback-helper-app#41]
Hi, 

it would be nice to controll your app with buttons.
I use the elgato Streamdeck and so I am searching for a appropiate method to control pushback. 
Programming my own pushbacksystem works, but not as smooth as yours. So now I'm thinking about the possibility to control your app via my Streamdeck (call the tug, then controll the four buttons, etc.) since I can send hotkeys with it.
Would that be possible?

Many thanks
sschw

**Comment by metindikbas** [comment]
Hello,

Unfortunately, I don't have Streamdeck to do the integration and test. However, it is an open source project so you can also contribute by adding your code into this one :)
